monitor.bluez.properties = {
  bluez5.enable-sbc-xq = true
  bluez5.enable-msbc = true
  bluez5.enable-hw-volume = true
  bluez5.hfphsp-backend = "native"
  bluez5.codecs = [ sbc_xq sbc ldac aptx ]
  bluez5.default.rate = 48000
  bluez5.roles = [ a2dp_sink a2dp_source ]
}

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
        bluez5.hw-volume = [ a2dp_sink ]
        device.profile = "a2dp-sink-sbc_xq"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        node.latency = 1024/48000
        node.pause-on-idle = false
      }
    }
  }
]
